name: arco_design_icons
description: Collection of beautiful and well-designed icons from Arco Design System
version: 0.0.1
homepage: https://github.com/hanmajid/arco_design_icons
issue_tracker: https://github.com/hanmajid/arco_design_icons/issues
repository: https://github.com/hanmajid/arco_design_icons

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: ArcoDesignIcons
      fonts:
        - asset: assets/ArcoDesignIcons.ttf

topics:
  - assets
  - icons
  - ui

screenshots:
  - description: 'Arco Design System icons'
    path: arco-design-icons.png