// Copyright 2023 hanmajid (Muhammad Farhan Majid)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:flutter/widgets.dart';

/// Class containing default Arco Design icons.
///
/// This font was generated by FlutterIcon.com.
class ArcoDesignIcons {
  /// No need for constructor. All properties are static.
  ArcoDesignIcons._();

  /// Default Arco Design icons family name.
  static const _kFontFam = 'ArcoDesignIcons';

  /// Arco Design icons package name.
  static const String? _kFontPkg = 'arco_design_icons';

  /// Icon data for 'align_center' glyph.
  static const IconData align_center =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'align_left' glyph.
  static const IconData align_left =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'align_right' glyph.
  static const IconData align_right =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'application' glyph.
  static const IconData application =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'apps' glyph.
  static const IconData apps =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'archive' glyph.
  static const IconData archive =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_down' glyph.
  static const IconData arrow_down =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_fall' glyph.
  static const IconData arrow_fall =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_left' glyph.
  static const IconData arrow_left =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_right' glyph.
  static const IconData arrow_right =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_rise' glyph.
  static const IconData arrow_rise =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_up' glyph.
  static const IconData arrow_up =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'at' glyph.
  static const IconData at =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'backward' glyph.
  static const IconData backward =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bg_colors' glyph.
  static const IconData bg_colors =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bold' glyph.
  static const IconData bold =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'book' glyph.
  static const IconData book =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'branch' glyph.
  static const IconData branch =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'brush' glyph.
  static const IconData brush =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bug' glyph.
  static const IconData bug =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bulb' glyph.
  static const IconData bulb =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'calendar' glyph.
  static const IconData calendar =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'camera' glyph.
  static const IconData camera =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'caret_left' glyph.
  static const IconData caret_left =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'caret_right' glyph.
  static const IconData caret_right =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'caret_up' glyph.
  static const IconData caret_up =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'caret_down' glyph.
  static const IconData caret_down =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'check_circle_fill' glyph.
  static const IconData check_circle_fill =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'check_circle' glyph.
  static const IconData check_circle =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'check' glyph.
  static const IconData check =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'check_square' glyph.
  static const IconData check_square =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'clock_circle' glyph.
  static const IconData clock_circle =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'close_circle_fill' glyph.
  static const IconData close_circle_fill =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'close_circle' glyph.
  static const IconData close_circle =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'circular' glyph.
  static const IconData circular =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'close' glyph.
  static const IconData close =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cloud_download' glyph.
  static const IconData cloud_download =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cloud' glyph.
  static const IconData cloud =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'code_block' glyph.
  static const IconData code_block =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'code_square' glyph.
  static const IconData code_square =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'code' glyph.
  static const IconData code =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'command' glyph.
  static const IconData command =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'common' glyph.
  static const IconData common =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'compass' glyph.
  static const IconData compass =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'copy' glyph.
  static const IconData copy =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'copyright' glyph.
  static const IconData copyright =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'customer_service' glyph.
  static const IconData customer_service =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dashboard' glyph.
  static const IconData dashboard =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'delete' glyph.
  static const IconData delete =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'desktop' glyph.
  static const IconData desktop =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dice' glyph.
  static const IconData dice =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'double_down' glyph.
  static const IconData double_down =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'double_left' glyph.
  static const IconData double_left =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'double_right' glyph.
  static const IconData double_right =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'down_circle' glyph.
  static const IconData down_circle =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'down' glyph.
  static const IconData down =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'download' glyph.
  static const IconData download =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'drag_arrow' glyph.
  static const IconData drag_arrow =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'drag_dot_vertical' glyph.
  static const IconData drag_dot_vertical =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'double_up' glyph.
  static const IconData double_up =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'drag_dot' glyph.
  static const IconData drag_dot =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'drive_file' glyph.
  static const IconData drive_file =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'ear' glyph.
  static const IconData ear =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'edit' glyph.
  static const IconData edit =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'email' glyph.
  static const IconData email =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'empty' glyph.
  static const IconData empty =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'exclamation_circle_fill' glyph.
  static const IconData exclamation_circle_fill =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'eraser' glyph.
  static const IconData eraser =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'exclamation_circle' glyph.
  static const IconData exclamation_circle =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'exclamation' glyph.
  static const IconData exclamation =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'exclamation_polygon_fill' glyph.
  static const IconData exclamation_polygon_fill =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'expand' glyph.
  static const IconData expand =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'export_icon' glyph.
  static const IconData export_icon =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'eye_invisible' glyph.
  static const IconData eye_invisible =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'experiment' glyph.
  static const IconData experiment =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'eye' glyph.
  static const IconData eye =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'face_meh_fill' glyph.
  static const IconData face_meh_fill =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'face_frown_fill' glyph.
  static const IconData face_frown_fill =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file_audio' glyph.
  static const IconData file_audio =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'face_smile_fill' glyph.
  static const IconData face_smile_fill =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file_image' glyph.
  static const IconData file_image =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file_pdf' glyph.
  static const IconData file_pdf =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file_video' glyph.
  static const IconData file_video =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file' glyph.
  static const IconData file =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'find_replace' glyph.
  static const IconData find_replace =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'fire' glyph.
  static const IconData fire =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'filter' glyph.
  static const IconData filter =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'folder_delete' glyph.
  static const IconData folder_delete =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'font_colors' glyph.
  static const IconData font_colors =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'folder' glyph.
  static const IconData folder =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'formula' glyph.
  static const IconData formula =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'folder_add' glyph.
  static const IconData folder_add =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'forward' glyph.
  static const IconData forward =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'fullscreen_exit' glyph.
  static const IconData fullscreen_exit =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'fullscreen' glyph.
  static const IconData fullscreen =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'gift' glyph.
  static const IconData gift =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'h1' glyph.
  static const IconData h1 =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'h2' glyph.
  static const IconData h2 =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'h3' glyph.
  static const IconData h3 =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'h4' glyph.
  static const IconData h4 =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'h5' glyph.
  static const IconData h5 =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'h6' glyph.
  static const IconData h6 =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'h7' glyph.
  static const IconData h7 =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heart_fill' glyph.
  static const IconData heart_fill =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heart' glyph.
  static const IconData heart =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'highlight' glyph.
  static const IconData highlight =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'history' glyph.
  static const IconData history =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'home' glyph.
  static const IconData home =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'idcard' glyph.
  static const IconData idcard =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'image_close' glyph.
  static const IconData image_close =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'image' glyph.
  static const IconData image =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'import_icon' glyph.
  static const IconData import_icon =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'info_circle_fill' glyph.
  static const IconData info_circle_fill =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'info_circle' glyph.
  static const IconData info_circle =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'info' glyph.
  static const IconData info =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'interaction' glyph.
  static const IconData interaction =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'italic' glyph.
  static const IconData italic =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'language' glyph.
  static const IconData language =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'launch' glyph.
  static const IconData launch =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'layout' glyph.
  static const IconData layout =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'left_circle' glyph.
  static const IconData left_circle =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'left' glyph.
  static const IconData left =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'line_height' glyph.
  static const IconData line_height =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'link' glyph.
  static const IconData link =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'list' glyph.
  static const IconData list =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'live_broadcast' glyph.
  static const IconData live_broadcast =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'loading' glyph.
  static const IconData loading =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'location' glyph.
  static const IconData location =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lock' glyph.
  static const IconData lock =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'loop' glyph.
  static const IconData loop =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'man' glyph.
  static const IconData man =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'menu_fold' glyph.
  static const IconData menu_fold =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'menu_unfold' glyph.
  static const IconData menu_unfold =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'menu' glyph.
  static const IconData menu =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'message_banned' glyph.
  static const IconData message_banned =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'message' glyph.
  static const IconData message =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mind_mapping' glyph.
  static const IconData mind_mapping =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'minus_circle_fill' glyph.
  static const IconData minus_circle_fill =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'minus_circle' glyph.
  static const IconData minus_circle =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'minus' glyph.
  static const IconData minus =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mobile' glyph.
  static const IconData mobile =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'moon_fill' glyph.
  static const IconData moon_fill =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'moon' glyph.
  static const IconData moon =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'more_vertical' glyph.
  static const IconData more_vertical =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'more' glyph.
  static const IconData more =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mosaic' glyph.
  static const IconData mosaic =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'music' glyph.
  static const IconData music =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mute_fill' glyph.
  static const IconData mute_fill =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mute' glyph.
  static const IconData mute =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'nav' glyph.
  static const IconData nav =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'notification_close' glyph.
  static const IconData notification_close =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'notification' glyph.
  static const IconData notification =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'oblique_line' glyph.
  static const IconData oblique_line =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'old_version' glyph.
  static const IconData old_version =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'ordered_list' glyph.
  static const IconData ordered_list =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'original_size' glyph.
  static const IconData original_size =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'paste' glyph.
  static const IconData paste =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pause_circle_fill' glyph.
  static const IconData pause_circle_fill =
      IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pause_circle' glyph.
  static const IconData pause_circle =
      IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pause' glyph.
  static const IconData pause =
      IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pen_fill' glyph.
  static const IconData pen_fill =
      IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pen' glyph.
  static const IconData pen =
      IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'phone' glyph.
  static const IconData phone =
      IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'play_arrow_fill' glyph.
  static const IconData play_arrow_fill =
      IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'play_arrow' glyph.
  static const IconData play_arrow =
      IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'play_circle_fill' glyph.
  static const IconData play_circle_fill =
      IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'play_circle' glyph.
  static const IconData play_circle =
      IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'plus_circle_fill' glyph.
  static const IconData plus_circle_fill =
      IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'plus_circle' glyph.
  static const IconData plus_circle =
      IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'plus' glyph.
  static const IconData plus =
      IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'poweroff' glyph.
  static const IconData poweroff =
      IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'printer' glyph.
  static const IconData printer =
      IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'public' glyph.
  static const IconData public =
      IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pushpin' glyph.
  static const IconData pushpin =
      IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'qrcode' glyph.
  static const IconData qrcode =
      IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'question_circle_fill' glyph.
  static const IconData question_circle_fill =
      IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'question_circle' glyph.
  static const IconData question_circle =
      IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'question' glyph.
  static const IconData question =
      IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'quote' glyph.
  static const IconData quote =
      IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'record_stop' glyph.
  static const IconData record_stop =
      IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'record' glyph.
  static const IconData record =
      IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'redo' glyph.
  static const IconData redo =
      IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'refresh' glyph.
  static const IconData refresh =
      IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'reply' glyph.
  static const IconData reply =
      IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'right_circle' glyph.
  static const IconData right_circle =
      IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'right' glyph.
  static const IconData right =
      IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'robot_add' glyph.
  static const IconData robot_add =
      IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'robot' glyph.
  static const IconData robot =
      IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'rotate_left' glyph.
  static const IconData rotate_left =
      IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'rotate_right' glyph.
  static const IconData rotate_right =
      IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'safe' glyph.
  static const IconData safe =
      IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'save' glyph.
  static const IconData save =
      IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'scan' glyph.
  static const IconData scan =
      IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'schedule' glyph.
  static const IconData schedule =
      IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'scissor' glyph.
  static const IconData scissor =
      IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'search' glyph.
  static const IconData search =
      IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'select_all' glyph.
  static const IconData select_all =
      IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'send' glyph.
  static const IconData send =
      IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'settings' glyph.
  static const IconData settings =
      IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'shake' glyph.
  static const IconData shake =
      IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'share_alt' glyph.
  static const IconData share_alt =
      IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'share_external' glyph.
  static const IconData share_external =
      IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'share_internal' glyph.
  static const IconData share_internal =
      IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'shrink' glyph.
  static const IconData shrink =
      IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'skin' glyph.
  static const IconData skin =
      IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'skip_next_fill' glyph.
  static const IconData skip_next_fill =
      IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'skip_next' glyph.
  static const IconData skip_next =
      IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'skip_previous_fill' glyph.
  static const IconData skip_previous_fill =
      IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'skip_previous' glyph.
  static const IconData skip_previous =
      IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sort_ascending' glyph.
  static const IconData sort_ascending =
      IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sort_descending' glyph.
  static const IconData sort_descending =
      IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sort' glyph.
  static const IconData sort =
      IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sound_fill' glyph.
  static const IconData sound_fill =
      IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sound' glyph.
  static const IconData sound =
      IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'stamp' glyph.
  static const IconData stamp =
      IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'star_fill' glyph.
  static const IconData star_fill =
      IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'star' glyph.
  static const IconData star =
      IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'stop' glyph.
  static const IconData stop =
      IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'storage' glyph.
  static const IconData storage =
      IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'strikethrough' glyph.
  static const IconData strikethrough =
      IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'subscribe_add' glyph.
  static const IconData subscribe_add =
      IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'subscribe' glyph.
  static const IconData subscribe =
      IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'subscribed' glyph.
  static const IconData subscribed =
      IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sun_fill' glyph.
  static const IconData sun_fill =
      IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sun' glyph.
  static const IconData sun =
      IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'swap' glyph.
  static const IconData swap =
      IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sync_icon' glyph.
  static const IconData sync_icon =
      IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'tag' glyph.
  static const IconData tag =
      IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'tags' glyph.
  static const IconData tags =
      IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'thumb_down_fill' glyph.
  static const IconData thumb_down_fill =
      IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'thumb_down' glyph.
  static const IconData thumb_down =
      IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'thumb_up_fill' glyph.
  static const IconData thumb_up_fill =
      IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'thumb_up' glyph.
  static const IconData thumb_up =
      IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'thunderbolt' glyph.
  static const IconData thunderbolt =
      IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'to_bottom' glyph.
  static const IconData to_bottom =
      IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'to_left' glyph.
  static const IconData to_left =
      IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'to_right' glyph.
  static const IconData to_right =
      IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'to_top' glyph.
  static const IconData to_top =
      IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'tool' glyph.
  static const IconData tool =
      IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'translate' glyph.
  static const IconData translate =
      IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'trophy' glyph.
  static const IconData trophy =
      IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'underline' glyph.
  static const IconData underline =
      IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'undo' glyph.
  static const IconData undo =
      IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'unlock' glyph.
  static const IconData unlock =
      IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'unordered_list' glyph.
  static const IconData unordered_list =
      IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'up_circle' glyph.
  static const IconData up_circle =
      IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'up' glyph.
  static const IconData up =
      IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'upload' glyph.
  static const IconData upload =
      IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_add' glyph.
  static const IconData user_add =
      IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_group' glyph.
  static const IconData user_group =
      IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user' glyph.
  static const IconData user =
      IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'video_camera' glyph.
  static const IconData video_camera =
      IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'voice' glyph.
  static const IconData voice =
      IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'wifi' glyph.
  static const IconData wifi =
      IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'woman' glyph.
  static const IconData woman =
      IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'zoom_in' glyph.
  static const IconData zoom_in =
      IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'zoom_out' glyph.
  static const IconData zoom_out =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
